apiVersion: apps/v1
kind: Deployment
metadata:
  name: finenice-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finenice-frontend
  template:
    metadata:
      labels:
        app: finenice-frontend
    spec:
      containers:
        - name: frontend
          image: finenice-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: finenice-frontend-service
spec:
  type: NodePort
  selector:
    app: finenice-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
